environment = "JULIA_DEPOT_PATH='/lustre/fs24/group/cqta/tangelides/.julia:$JULIA_DEPOT_PATH'"

executable = /lustre/fs24/group/cqta/tangelides/julia-1.8.5/bin/julia

arguments = /lustre/fs24/group/cqta/tangelides/SW_MPS_iT/SW_Observables_iT.jl $(N) $(x) $(mg) $(D) $(l_0) $(lambda) $(acc) $(ns) $(w_1_s_2) $(first_excited)

transfer_input_files = /lustre/fs24/group/cqta/tangelides/SW_MPS_iT/SW_Observables_iT.jl

should_transfer_files = IF_NEEDED

max_retries = 5

error = /lustre/fs24/group/cqta/tangelides/Logs/$(Cluster)_$(Process)_N_$(N)_x_$(x)_D_$(D)_l0_$(l_0)_mg_$(mg)_ns_$(ns)_acc_$(acc)_lam_$(lambda)_w1s2_$(w_1_s_2)_fe_$(first_excited).error

# output = /lustre/fs24/group/cqta/tangelides/Logs/$(Cluster)_$(Process)_N_$(N)_x_$(x)_D_$(D)_l0_$(l_0)_mg_$(mg)_ns_$(ns)_acc_$(acc)_lam_$(lambda)_w1s2_$(w_1_s_2)_fe_$(first_excited).out                    

# log = /lustre/fs24/group/cqta/tangelides/Logs/$(Cluster)_$(Process)_N_$(N)_x_$(x)_D_$(D)_l0_$(l_0)_mg_$(mg)_ns_$(ns)_acc_$(acc)_lam_$(lambda)_w1s2_$(w_1_s_2)_fe_$(first_excited).log 

queue